/**
 * Regenerates `src/tokens.gen.ts` from the installed `tailwindcss`.
 *
 *   pnpm --filter @react-native-rethemed/tailwind-css-tokens generate
 *
 * Bump the `tailwindcss` devDependency version, run this, and review the
 * diff. Not exported from the package.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type ConvertedTheme, convertTheme } from './convert';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../src/tokens.gen.ts');

// `theme.css` and `package.json` are not in the package's `exports`; find
// them next to its entry point (`dist/lib.js`).
const tailwindRoot = resolve(dirname(require.resolve('tailwindcss')), '..');
const themeCss = readFileSync(resolve(tailwindRoot, 'theme.css'), 'utf8');
const tailwindVersion: string = JSON.parse(
  readFileSync(resolve(tailwindRoot, 'package.json'), 'utf8'),
).version;

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const NUMERIC_KEY = /^\d+(\.\d+)?$/;

function key(name: string): string {
  if (IDENTIFIER.test(name)) return name;
  if (NUMERIC_KEY.test(name) && String(Number(name)) === name) return name;
  return `'${name}'`;
}

function literal(value: unknown, indent: string): string {
  if (typeof value === 'string') return `'${value.replaceAll("'", "\\'")}'`;
  if (typeof value === 'number') return String(value);
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    // Small flat objects (`shadowOffset`) stay on one line.
    if (entries.every(([, v]) => typeof v !== 'object')) {
      const inline = `{ ${entries.map(([k, v]) => `${key(k)}: ${literal(v, indent)}`).join(', ')} }`;
      if (inline.length <= 40) return inline;
    }
    const inner = `${indent}  `;
    const lines = entries.map(
      ([k, v]) => `${inner}${key(k)}: ${literal(v, inner)},`,
    );
    return `{\n${lines.join('\n')}\n${indent}}`;
  }
  throw new Error(`cannot emit ${String(value)}`);
}

/**
 * Named keys (`px`) first, then numeric keys (spacing) in value order.
 * Returns entries, since an object would move integer keys first again. At
 * runtime the object literal still lists integer keys first; the order here
 * only affects how the generated source reads.
 */
function ordered<T>(record: Record<string, T>): [string, T][] {
  const entries = Object.entries(record);
  const numeric = entries.filter(([k]) => NUMERIC_KEY.test(k));
  if (numeric.length === 0) return entries;
  numeric.sort(([a], [b]) => Number(a) - Number(b));
  return [...entries.filter(([k]) => !NUMERIC_KEY.test(k)), ...numeric];
}

function emitConst(
  name: keyof ConvertedTheme,
  value: Record<string, unknown>,
  doc: string,
  satisfies?: string,
): string {
  const lines = ordered(value).map(
    ([k, v]) => `  ${key(k)}: ${literal(v, '  ')},`,
  );
  const suffix = satisfies ? ` as const satisfies ${satisfies}` : ' as const';
  return `/** ${doc} */\nexport const ${name} = {\n${lines.join('\n')}\n}${suffix};\n`;
}

const theme = convertTheme(themeCss);

const source = [
  `// Generated by scripts/generate.ts from tailwindcss@${tailwindVersion} (theme.css).`,
  '// Do not edit by hand: run `pnpm generate` instead.',
  '',
  'import type {',
  '  ShadowToken,',
  '  TextToken,',
  "} from '@react-native-rethemed/core/config';",
  '',
  emitConst(
    'colors',
    theme.colors,
    "Tailwind's palette (`--color-*`), converted from oklch to hex: `'<hue>.<shade>'`, plus `black` and `white`.",
  ),
  emitConst(
    'spacing',
    theme.spacing,
    "`--spacing` (0.25rem) × n for the steps in Tailwind's docs: `padding: 4` is `p-4` (16). `px` is 1.",
  ),
  emitConst(
    'radii',
    theme.radii,
    '`--radius-*` in points, plus the `rounded-none` / `rounded-full` utilities.',
  ),
  emitConst('fontSizes', theme.fontSizes, '`--text-*` sizes in points.'),
  emitConst('fontWeights', theme.fontWeights, '`--font-weight-*`.'),
  emitConst(
    'lineHeights',
    theme.lineHeights,
    '`--leading-*` as ratios of `fontSize`, plus the `leading-none` utility.',
  ),
  emitConst(
    'letterSpacings',
    theme.letterSpacings,
    '`--tracking-*`: em values converted to points at a 16px font size.',
  ),
  emitConst(
    'shadows',
    theme.shadows,
    '`--shadow-*` as single-layer RN shadows (first layer).',
    'Record<string, ShadowToken>',
  ),
  emitConst(
    'text',
    theme.text,
    '`text-*` as presets: each size with its paired `--text-*--line-height`, made absolute.',
    'Record<string, TextToken>',
  ),
].join('\n');

writeFileSync(outFile, source);

// Let biome settle line breaks so the file passes `pnpm lint`.
execFileSync(
  process.execPath,
  [require.resolve('@biomejs/biome/bin/biome'), 'format', '--write', outFile],
  { stdio: 'inherit' },
);

console.log(`Wrote ${outFile} (tailwindcss@${tailwindVersion})`);
