import { defineTheme } from '@react-native-rethemed/core/config';
import {
  colors,
  fontSizes,
  fontWeights,
  letterSpacings,
  lineHeights,
  radii,
  shadows,
  spacing,
  text,
} from './tokens.gen';

/**
 * Tailwind CSS's default theme (`tailwindcss/theme.css`), converted for
 * React Native with Tailwind's names. Values are generated by
 * `scripts/generate.ts`; see `src/tokens.gen.ts`.
 *
 * - Lengths: rem → points at 16px; em letter spacings → points at 16px.
 * - `colors`: the oklch palette as hex, `'<hue>.<shade>'` (`'sky.500'`).
 *   Fixed in both schemes: Tailwind has no semantic colors (it uses `dark:`
 *   variants), so define `semanticTokens.colors` in the app.
 * - `spacing`: `padding: 4` is `p-4` (16), for the steps Tailwind's docs
 *   list. `radii` / `lineHeights` add the `rounded-none` / `rounded-full` /
 *   `leading-none` utilities.
 * - `text`: `themed.text.sm()` is `text-sm` — font size plus its paired line
 *   height. `fontSizes` (`fontSize: 'sm'`) sets the size alone.
 * - `defaults.fontSize` is `base` (16), the size `lineHeights` ratios use when
 *   a style has no `fontSize` of its own.
 * - `shadows`: first layer only. Not included (no RN equivalent): fonts,
 *   inset / drop / text shadows, blur, perspective, easing, animations,
 *   aspect ratios, breakpoints, containers.
 *
 * The palette, radii and shadows are the same values as
 * `@react-native-rethemed/panda-css-tokens` (Panda's preset uses Tailwind's).
 */
export const tailwindCssTheme = defineTheme({
  tokens: {
    colors,
    radii,
    spacing,
    fontSizes,
    fontWeights,
    lineHeights,
    letterSpacings,
    shadows,
  },
  semanticTokens: {
    text,
  },
  defaults: {
    fontSize: 'base',
  },
});

export {
  colors,
  fontSizes,
  fontWeights,
  letterSpacings,
  lineHeights,
  radii,
  shadows,
  spacing,
  text,
};
