packages:
  - apps/*
  - packages/*
  - packages/react-native-rethemed/*

catalog:
  react-native: 0.86.2
  react: 19.2.3
  react-dom: 19.2.3

allowBuilds:
  esbuild: true
  lefthook: true
  msw: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
