import { defineTheme } from '@react-native-rethemed/core/config';
import {
  colors,
  fontWeights,
  radii,
  semanticColors,
  shadows,
  spacing,
  typography,
  zIndices,
} from './tokens.gen';

/**
 * Material UI's default theme (`createTheme()` from `@mui/material`, which
 * follows Material Design 2), converted for React Native. Values are
 * generated by `scripts/generate.ts`; see `src/tokens.gen.ts`.
 *
 * - `semanticColors`: the default `palette` in light and dark mode, as
 *   `'<group>.<key>'` with Material UI's own names: `'primary.main'`,
 *   `'primary.contrastText'`, `'text.secondary'`, `'background.paper'`,
 *   `'action.hover'`, `'divider.default'`.
 * - `colors`: `@mui/material/colors` as `'<hue>.<shade>'` (`'red.500'`,
 *   `'deepPurple.A200'`), plus `black` and `white`. Fixed in both schemes.
 * - `typography`: the 13 variants (`h1`…`overline`) as text presets,
 *   `themed.text.h1()`. rem/em → points at `htmlFontSize` (16); line heights
 *   absolute; `button` / `overline` keep `textTransform: 'uppercase'`.
 * - `spacing`: `theme.spacing(n)`, so `padding: 2` is 16. `radii`: multiples
 *   of `shape.borderRadius`, so `borderRadius: 2` is 8 — both like `sx`.
 * - `shadows`: elevations 0–24, first layer only; `elevation` matches the
 *   Material elevation on Android exactly.
 * - Not included (no RN equivalent): `fontFamily` (Roboto, Android's default
 *   anyway), breakpoints, transitions, mixins, component overrides, the
 *   `action.*Opacity` numbers and dark mode's `text.icon`.
 */
export const materialUiTheme = defineTheme({
  tokens: {
    colors,
    radii,
    spacing,
    fontWeights,
    zIndices,
    shadows,
  },
  semanticTokens: {
    colors: semanticColors,
    text: typography,
  },
});

export {
  colors,
  fontWeights,
  radii,
  semanticColors,
  shadows,
  spacing,
  typography,
  zIndices,
};
