import { defineTheme } from '@react-native-rethemed/core/config';
import {
  colors,
  fontSizes,
  fontWeights,
  letterSpacings,
  lineHeights,
  radii,
  shadows,
  spacing,
} from './tokens.gen';

/**
 * Panda CSS's default theme (`@pandacss/preset-panda`), converted for React
 * Native. Values are generated by `scripts/generate.ts`; see
 * `src/tokens.gen.ts`.
 *
 * - Lengths: rem → points at 16px; em letter spacings → points at 16px.
 * - `colors`: Panda's (Tailwind's) oklch palette as hex. Color props take
 *   them by name (`themed.view({ backgroundColor: 'red.500' })`).
 * - `shadows`: first layer only; inset shadows are omitted.
 * - No `semanticTokens`: Panda ships none. Define `semanticTokens.colors`
 *   and `semanticTokens.text` in the app (they can reference these values).
 *   Panda's `textStyles` are not converted for the same reason.
 * - Not included (no RN style equivalent): sizes, fonts, blurs, durations,
 *   easings, animations, aspect ratios, borders, breakpoints, keyframes.
 */
export const pandaCssTheme = defineTheme({
  tokens: {
    colors,
    radii,
    spacing,
    fontSizes,
    fontWeights,
    lineHeights,
    letterSpacings,
    shadows,
  },
  // The browser default (16px); `lineHeights` are ratios of it when a style
  // has no `fontSize` of its own.
  defaults: {
    fontSize: 'md',
  },
});

export {
  colors,
  fontSizes,
  fontWeights,
  letterSpacings,
  lineHeights,
  radii,
  shadows,
  spacing,
};
