/**
 * Regenerates `src/tokens.gen.ts` from the installed `@radix-ui/themes`
 * (its published `tokens/base.css` and `tokens/colors/*.css`).
 *
 *   pnpm --filter @react-native-rethemed/radix-ui-tokens generate
 *
 * Bump the `@radix-ui/themes` devDependency version, run this, and review
 * the diff. Not exported from the package.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  type ConvertedTokens,
  convertTokens,
  SCALES,
  type ScaleName,
} from './convert';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../src/tokens.gen.ts');

const read = (file: string) =>
  readFileSync(require.resolve(`@radix-ui/themes/${file}`), 'utf8');
const radixVersion: string = JSON.parse(read('package.json')).version;

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const NUMERIC_KEY = /^\d+(\.\d+)?$/;

function key(name: string): string {
  if (IDENTIFIER.test(name)) return name;
  if (NUMERIC_KEY.test(name) && String(Number(name)) === name) return name;
  return `'${name}'`;
}

function literal(value: unknown, indent: string): string {
  if (typeof value === 'string') return `'${value.replaceAll("'", "\\'")}'`;
  if (typeof value === 'number') return String(value);
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    // Small flat objects (`{ light, dark }`) stay on one line.
    if (entries.every(([, v]) => typeof v !== 'object')) {
      const inline = `{ ${entries.map(([k, v]) => `${key(k)}: ${literal(v, indent)}`).join(', ')} }`;
      if (inline.length <= 60) return inline;
    }
    const inner = `${indent}  `;
    const lines = entries.map(
      ([k, v]) => `${inner}${key(k)}: ${literal(v, inner)},`,
    );
    return `{\n${lines.join('\n')}\n${indent}}`;
  }
  throw new Error(`cannot emit ${String(value)}`);
}

/**
 * Named keys (`px`) first, then numeric keys (spacing) in value order.
 * Returns entries, since an object would move integer keys first again. At
 * runtime the object literal still lists integer keys first; the order here
 * only affects how the generated source reads.
 */
function ordered<T>(record: Record<string, T>): [string, T][] {
  const entries = Object.entries(record);
  const numeric = entries.filter(([k]) => NUMERIC_KEY.test(k));
  if (numeric.length === 0) return entries;
  numeric.sort(([a], [b]) => Number(a) - Number(b));
  return [...entries.filter(([k]) => !NUMERIC_KEY.test(k)), ...numeric];
}

function emitConst(
  name: keyof ConvertedTokens,
  value: Record<string, unknown>,
  doc: string,
  satisfies?: string,
): string {
  const lines = ordered(value).map(
    ([k, v]) => `  ${key(k)}: ${literal(v, '  ')},`,
  );
  const suffix = satisfies ? ` as const satisfies ${satisfies}` : ' as const';
  return `/** ${doc} */\nexport const ${name} = {\n${lines.join('\n')}\n}${suffix};\n`;
}

const tokens = convertTokens(
  read('tokens/base.css'),
  Object.fromEntries(
    SCALES.map((name) => [name, read(`tokens/colors/${name}.css`)]),
  ) as Record<ScaleName, string>,
);

const source = [
  `// Generated by scripts/generate.ts from @radix-ui/themes@${radixVersion} (tokens/*.css).`,
  '// Do not edit by hand: run `pnpm generate` instead.',
  '',
  emitConst(
    'scales',
    tokens.scales,
    'Every color scale: steps `1`–`12`, alpha `a1`–`a12`, and `contrast` / `surface` / `indicator` / `track`, each in light and dark (sRGB hex).',
  ),
  emitConst(
    'backgroundColors',
    tokens.backgroundColors,
    "`--color-*` per scheme: hex, or `'gray.<step>'` for the theme's gray.",
  ),
  emitConst('space', tokens.space, '`--space-*` in px at 100% scaling.'),
  emitConst(
    'fontSizes',
    tokens.fontSizes,
    '`--font-size-*` in px at 100% scaling.',
  ),
  emitConst(
    'lineHeights',
    tokens.lineHeights,
    '`--line-height-*` (Text) in px at 100% scaling.',
  ),
  emitConst(
    'headingLineHeights',
    tokens.headingLineHeights,
    '`--heading-line-height-*` (Heading) in px at 100% scaling.',
  ),
  emitConst(
    'letterSpacings',
    tokens.letterSpacings,
    '`--letter-spacing-*` in em.',
  ),
  `/** \`--heading-letter-spacing\` in em, added to \`--letter-spacing-*\` for Heading. */\nexport const headingLetterSpacing = ${tokens.headingLetterSpacing};\n`,
  emitConst('fontWeights', tokens.fontWeights, '`--font-weight-*`.'),
  emitConst(
    'radii',
    tokens.radii,
    '`--radius-*` in px at 100% scaling and radius factor 1.',
  ),
  emitConst(
    'radiusFactors',
    tokens.radiusFactors,
    '`--radius-factor` per `<Theme radius>`.',
  ),
  emitConst(
    'radiusFull',
    tokens.radiusFull,
    '`--radius-full` per `<Theme radius>` (9999 only for `full`).',
  ),
  emitConst('scalings', tokens.scalings, '`--scaling` per `<Theme scaling>`.'),
  emitConst(
    'shadows',
    tokens.shadows,
    "`--shadow-*` (light), one layer each: rings skipped, largest blur kept. `shadow-1` is inset and omitted. A `'gray.<step>'` color is the theme's gray.",
  ),
].join('\n');

writeFileSync(outFile, source);

// Let biome settle line breaks so the file passes `pnpm lint`.
execFileSync(
  process.execPath,
  [require.resolve('@biomejs/biome/bin/biome'), 'format', '--write', outFile],
  { stdio: 'inherit' },
);

console.log(`Wrote ${outFile} (@radix-ui/themes@${radixVersion})`);
