// Code generated by @react-native-rethemed/cli. DO NOT EDIT.
// Regenerate with: react-native-rethemed codegen src/__fixtures__/theme.ts

import type { TextStyle } from 'react-native';
import { createThemed, type TokenizeStyle } from '@react-native-rethemed/core';
import { themeConfig } from './theme';

// ---------------------------------------------------------------------------
// Token names
// ---------------------------------------------------------------------------

export type SemanticColorToken = 'bg.default' | 'bg.subtle' | 'fg.default' | 'fg.muted';
export type PrimitiveColorToken = 'white' | 'gray.950';
/** Color props take both: semantic colors switch with light/dark, primitives are fixed. */
export type ColorToken = SemanticColorToken | PrimitiveColorToken;
export type RadiusToken = 'none' | 'md' | 'full';
export type SpacingToken =
  | 0
  | 'px'
  | 0.5
  | 1
  | 2
  | 4;
export type FontSizeToken = 'sm' | 'md' | 'lg';
export type FontWeightToken = 'normal' | 'semibold';
export type LineHeightToken = 'short' | 'moderate';
export type LetterSpacingToken = 'tight' | 'wide';
export type ShadowToken = 'sm';
export type ZIndexToken = 'base' | 'modal';

// ---------------------------------------------------------------------------
// Token-aware style props. Each primitive picks the ones its RN style type
// has (see `TokenizeStyle` in core), so e.g. `color` never shows on View.
// ---------------------------------------------------------------------------

export interface ThemedStyleProps {
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  color?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  backgroundColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderTopColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderBottomColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderLeftColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderRightColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderStartColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderEndColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderBlockColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderBlockStartColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  borderBlockEndColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  tintColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  overlayColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  shadowColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  outlineColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  textShadowColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.default` | #ffffff | #111111 |
   * | `bg.subtle` | #fafafa | #18181b |
   * | `fg.default` | #111111 | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark. A grid cell is the token `'<hue>.<shade>'`, e.g. `'gray.950'`.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   *
   * | hue | 950 |
   * |:--|:--|
   * | `gray` | #111111 |
   */
  textDecorationColor?: ColorToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderTopLeftRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderTopRightRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderTopStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderTopEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderBottomLeftRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderBottomRightRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderBottomStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderBottomEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderStartStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderStartEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderEndStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `none` | 0 |
   * | `md` | 6 |
   * | `full` | 9999 |
   */
  borderEndEndRadius?: RadiusToken;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  padding?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingTop?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingBottom?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingLeft?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingRight?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingHorizontal?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingVertical?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingBlock?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingBlockStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingBlockEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingInline?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingInlineStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  paddingInlineEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  margin?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginTop?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginBottom?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginLeft?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginRight?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginHorizontal?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginVertical?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginBlock?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginBlockStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginBlockEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginInline?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginInlineStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  marginInlineEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  gap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  rowGap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `px` | 1 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `2` | 8 |
   * | `4` | 16 |
   */
  columnGap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.fontSizes`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 14 |
   * | `md` | 16 |
   * | `lg` | 18 |
   */
  fontSize?: FontSizeToken | number;
  /**
   * `tokens.fontWeights`
   *
   * | token | value |
   * |:--|--:|
   * | `normal` | 400 |
   * | `semibold` | 600 |
   */
  fontWeight?: FontWeightToken | TextStyle['fontWeight'];
  /**
   * Ratios of `fontSize`: a token resolves to `fontSize × ratio`, using the style's own `fontSize` or else the default font size, `md` (16). A raw number is an absolute line height.
   *
   * `tokens.lineHeights`
   *
   * | token | value |
   * |:--|--:|
   * | `short` | ×1.375 |
   * | `moderate` | ×1.5 |
   */
  lineHeight?: LineHeightToken | number;
  /**
   * `tokens.letterSpacings`
   *
   * | token | value |
   * |:--|--:|
   * | `tight` | -0.4 |
   * | `wide` | 0.4 |
   */
  letterSpacing?: LetterSpacingToken | number;
  /**
   * `tokens.zIndices`
   *
   * | token | value |
   * |:--|--:|
   * | `base` | 0 |
   * | `modal` | 1400 |
   */
  zIndex?: ZIndexToken | number;
  /**
   * Virtual prop: expands to `shadowColor` / `shadowOffset` / `shadowOpacity` / `shadowRadius` / `elevation`.
   *
   * `tokens.shadows`
   *
   * | token | offset (x, y) | radius | opacity | elevation | color |
   * |:--|--:|--:|--:|--:|:--|
   * | `sm` | 0, 1 | 2 | 0.1 | 2 | #000000 |
   */
  shadow?: ShadowToken;
}

// ---------------------------------------------------------------------------
// Typography presets: themed.text.<path>(override?)
// ---------------------------------------------------------------------------

type TextVariant = (
  override?: TokenizeStyle<TextStyle, ThemedStyleProps>,
) => TextStyle;

export interface ThemedTextVariants {
  /**
   * `semanticTokens.text.title`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `title.md` | `md` (16) | 24 | 0.15 | `semibold` (600) |
   * | `title.sm` | 14 | 20 | – | 500 |
   */
  title: {
    /**
     * `semanticTokens.text.title.md`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | `md` (16) | 24 | 0.15 | `semibold` (600) |
     */
    md: TextVariant;
    /**
     * `semanticTokens.text.title.sm`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 14 | 20 | – | 500 |
     */
    sm: TextVariant;
  };
  /**
   * `semanticTokens.text.body`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `body.md` | `sm` (14) | `moderate` (×1.5 → 21) | – | – |
   */
  body: {
    /**
     * `semanticTokens.text.body.md`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | `sm` (14) | `moderate` (×1.5 → 21) | – | – |
     */
    md: TextVariant;
  };
  /**
   * `semanticTokens.text.caption`
   *
   * | fontSize | lineHeight | letterSpacing | fontWeight | color |
   * |--:|--:|--:|--:|:--|
   * | `sm` (14) | – | `wide` (0.4) | – | light: #71717a, dark: #a1a1aa |
   */
  caption: TextVariant;
  /**
   * `semanticTokens.text.heading`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight | color |
   * |:--|--:|--:|--:|--:|:--|
   * | `heading.page` | `lg` (18) | `short` (×1.375 → 24.75) | – | – | dark: #fafafa |
   */
  heading: {
    /**
     * `semanticTokens.text.heading.display`
     *
     * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
     * |:--|--:|--:|--:|--:|
     * | `heading.display.lg` | 36 | 44 | – | `semibold` (600) |
     */
    display: {
      /**
       * `semanticTokens.text.heading.display.lg`
       *
       * | fontSize | lineHeight | letterSpacing | fontWeight |
       * |--:|--:|--:|--:|
       * | 36 | 44 | – | `semibold` (600) |
       */
      lg: TextVariant;
    };
    /**
     * `semanticTokens.text.heading.page`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight | color |
     * |--:|--:|--:|--:|:--|
     * | `lg` (18) | `short` (×1.375 → 24.75) | – | – | dark: #fafafa |
     */
    page: TextVariant;
  };
}

// ---------------------------------------------------------------------------
// useThemed().tokens / useThemed().semanticTokens
// ---------------------------------------------------------------------------

export interface ThemedTokens {
  colors: {
    white: '#ffffff';
    'gray.950': '#111111';
  };
  radii: {
    none: 0;
    md: 6;
    full: 9999;
  };
  spacing: {
    0: 0;
    1: 4;
    2: 8;
    4: 16;
    px: 1;
    0.5: 2;
  };
  fontSizes: {
    sm: 14;
    md: 16;
    lg: 18;
  };
  fontWeights: {
    normal: '400';
    semibold: '600';
  };
  lineHeights: {
    short: 1.375;
    moderate: 1.5;
  };
  letterSpacings: {
    tight: -0.4;
    wide: 0.4;
  };
  zIndices: {
    base: 0;
    modal: 1400;
  };
  shadows: {
    sm: {
      shadowColor: '#000000';
      shadowOffset: {
        width: 0;
        height: 1;
      };
      shadowOpacity: 0.1;
      shadowRadius: 2;
      elevation: 2;
    };
  };
}

export interface ThemedSemanticTokens {
  /** Resolved for the current color scheme. */
  colors: {
    bg: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffff | #111111 |
       */
      default: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #fafafa | #18181b |
       */
      subtle: string;
    };
    fg: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #111111 | #fafafa |
       */
      default: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #52525b | #a1a1aa |
       */
      muted: string;
    };
  };
  text: {
    title: {
      md: {
        fontSize: 'md';
        lineHeight: 24;
        letterSpacing: 0.15;
        fontWeight: 'semibold';
      };
      sm: {
        fontSize: 14;
        lineHeight: 20;
        fontWeight: '500';
      };
    };
    body: {
      md: {
        fontSize: 'sm';
        lineHeight: 'moderate';
      };
    };
    caption: {
      fontSize: 'sm';
      letterSpacing: 'wide';
      color: '#71717a' | '#a1a1aa';
    };
    heading: {
      display: {
        lg: {
          fontSize: 36;
          lineHeight: 44;
          fontWeight: 'semibold';
        };
      };
      page: {
        fontSize: 'lg';
        lineHeight: 'short';
        color: '#fafafa' | undefined;
      };
    };
  };
}

// ---------------------------------------------------------------------------
// Instance
// ---------------------------------------------------------------------------

export interface ThemedTypes {
  style: ThemedStyleProps;
  textVariants: ThemedTextVariants;
  tokens: ThemedTokens;
  semanticTokens: ThemedSemanticTokens;
}

export const { ThemedProvider, useThemed, useColorMode } =
  createThemed<ThemedTypes>(themeConfig);
