// Code generated by @react-native-rethemed/cli. DO NOT EDIT.
// Regenerate with: react-native-rethemed codegen example/theme.ts --docs example/themed.md

import type { TextStyle } from 'react-native';
import { createThemed, type TokenizeStyle } from '@react-native-rethemed/core';
import { themeConfig } from './theme';

// ---------------------------------------------------------------------------
// Token names
// ---------------------------------------------------------------------------

export type SemanticColorToken =
  | 'accent.1'
  | 'accent.2'
  | 'accent.3'
  | 'accent.4'
  | 'accent.5'
  | 'accent.6'
  | 'accent.7'
  | 'accent.8'
  | 'accent.9'
  | 'accent.10'
  | 'accent.11'
  | 'accent.12'
  | 'accent.a1'
  | 'accent.a2'
  | 'accent.a3'
  | 'accent.a4'
  | 'accent.a5'
  | 'accent.a6'
  | 'accent.a7'
  | 'accent.a8'
  | 'accent.a9'
  | 'accent.a10'
  | 'accent.a11'
  | 'accent.a12'
  | 'accent.surface'
  | 'accent.indicator'
  | 'accent.track'
  | 'accent.contrast'
  | 'gray.1'
  | 'gray.2'
  | 'gray.3'
  | 'gray.4'
  | 'gray.5'
  | 'gray.6'
  | 'gray.7'
  | 'gray.8'
  | 'gray.9'
  | 'gray.10'
  | 'gray.11'
  | 'gray.12'
  | 'gray.a1'
  | 'gray.a2'
  | 'gray.a3'
  | 'gray.a4'
  | 'gray.a5'
  | 'gray.a6'
  | 'gray.a7'
  | 'gray.a8'
  | 'gray.a9'
  | 'gray.a10'
  | 'gray.a11'
  | 'gray.a12'
  | 'gray.surface'
  | 'gray.indicator'
  | 'gray.track'
  | 'gray.contrast'
  | 'color.background'
  | 'color.overlay'
  | 'color.panel-solid'
  | 'color.panel-translucent'
  | 'color.surface';
export type PrimitiveColorToken = never;
/** Color props take both: semantic colors switch with light/dark, primitives are fixed. */
export type ColorToken = SemanticColorToken | PrimitiveColorToken;
export type RadiusToken =
  | 'full'
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6;
export type SpacingToken =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9;
export type FontSizeToken =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9;
export type FontWeightToken = 'light' | 'regular' | 'medium' | 'bold';
export type LineHeightToken = never;
export type LetterSpacingToken = never;
export type ShadowToken =
  | 2
  | 3
  | 4
  | 5
  | 6;
export type ZIndexToken = never;

// ---------------------------------------------------------------------------
// Token-aware style props. Each primitive picks the ones its RN style type
// has (see `TokenizeStyle` in core), so e.g. `color` never shows on View.
// ---------------------------------------------------------------------------

export interface ThemedStyleProps {
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  color?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  backgroundColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderTopColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderBottomColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderLeftColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderRightColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderStartColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderEndColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderBlockColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderBlockStartColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  borderBlockEndColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  tintColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  overlayColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  shadowColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  outlineColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  textShadowColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `accent.1` | #fdfdfe | #11131f |
   * | `accent.2` | #f7f9ff | #141726 |
   * | `accent.3` | #edf2fe | #182449 |
   * | `accent.4` | #e1e9ff | #1d2e62 |
   * | `accent.5` | #d2deff | #253974 |
   * | `accent.6` | #c1d0ff | #304384 |
   * | `accent.7` | #abbdf9 | #3a4f97 |
   * | `accent.8` | #8da4ef | #435db1 |
   * | `accent.9` | #3e63dd | #3e63dd |
   * | `accent.10` | #3358d4 | #5472e4 |
   * | `accent.11` | #3a5bc7 | #9eb1ff |
   * | `accent.12` | #1f2d5c | #d6e1ff |
   * | `accent.a1` | #00008002 | #1133ff0f |
   * | `accent.a2` | #0040ff08 | #3354fa17 |
   * | `accent.a3` | #0047f112 | #2f62ff3c |
   * | `accent.a4` | #0044ff1e | #3566ff57 |
   * | `accent.a5` | #0044ff2d | #4171fd6b |
   * | `accent.a6` | #003eff3e | #5178fd7c |
   * | `accent.a7` | #0037ed54 | #5a7fff90 |
   * | `accent.a8` | #0034dc72 | #5b81feac |
   * | `accent.a9` | #0031d2c1 | #4671ffdb |
   * | `accent.a10` | #002ec9cc | #5c7efee3 |
   * | `accent.a11` | #002bb7c5 | #9eb1ff |
   * | `accent.a12` | #001046e0 | #d6e1ff |
   * | `accent.surface` | #f5f8ffcc | #171d3b80 |
   * | `accent.indicator` | #3e63dd | #3e63dd |
   * | `accent.track` | #3e63dd | #3e63dd |
   * | `accent.contrast` | #ffffff | #ffffff |
   * | `gray.1` | #fcfcfd | #111113 |
   * | `gray.2` | #f9f9fb | #18191b |
   * | `gray.3` | #f0f0f3 | #212225 |
   * | `gray.4` | #e8e8ec | #272a2d |
   * | `gray.5` | #e0e1e6 | #2e3135 |
   * | `gray.6` | #d9d9e0 | #363a3f |
   * | `gray.7` | #cdced6 | #43484e |
   * | `gray.8` | #b9bbc6 | #5a6169 |
   * | `gray.9` | #8b8d98 | #696e77 |
   * | `gray.10` | #80838d | #777b84 |
   * | `gray.11` | #60646c | #b0b4ba |
   * | `gray.12` | #1c2024 | #edeef0 |
   * | `gray.a1` | #00005503 | #00000000 |
   * | `gray.a2` | #00005506 | #d8f4f609 |
   * | `gray.a3` | #0000330f | #ddeaf814 |
   * | `gray.a4` | #00002d17 | #d3edf81d |
   * | `gray.a5` | #0009321f | #d9edfe25 |
   * | `gray.a6` | #00002f26 | #d6ebfd30 |
   * | `gray.a7` | #00062e32 | #d9edff40 |
   * | `gray.a8` | #00083046 | #d9edff5d |
   * | `gray.a9` | #00051d74 | #dfebfd6d |
   * | `gray.a10` | #00071b7f | #e5edfd7b |
   * | `gray.a11` | #0007149f | #f1f7feb5 |
   * | `gray.a12` | #000509e3 | #fcfdffef |
   * | `gray.surface` | #ffffffcc | #1f212380 |
   * | `gray.indicator` | #8b8d98 | #696e77 |
   * | `gray.track` | #8b8d98 | #696e77 |
   * | `gray.contrast` | #ffffff | #ffffff |
   * | `color.background` | #ffffff | #111113 |
   * | `color.overlay` | #00000066 | #00000099 |
   * | `color.panel-solid` | #ffffff | #18191b |
   * | `color.panel-translucent` | #ffffffb3 | #d8f4f609 |
   * | `color.surface` | #ffffffd9 | #00000040 |
   */
  textDecorationColor?: ColorToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderTopLeftRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderTopRightRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderTopStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderTopEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderBottomLeftRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderBottomRightRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderBottomStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderBottomEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderStartStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderStartEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderEndStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `full` | 0 |
   * | `1` | 3 |
   * | `2` | 4 |
   * | `3` | 6 |
   * | `4` | 8 |
   * | `5` | 12 |
   * | `6` | 16 |
   */
  borderEndEndRadius?: RadiusToken;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  padding?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingTop?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingBottom?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingLeft?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingRight?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingHorizontal?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingVertical?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingBlock?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingBlockStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingBlockEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingInline?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingInlineStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  paddingInlineEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  margin?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginTop?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginBottom?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginLeft?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginRight?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginHorizontal?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginVertical?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginBlock?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginBlockStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginBlockEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginInline?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginInlineStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  marginInlineEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  gap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  rowGap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 4 |
   * | `2` | 8 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 24 |
   * | `6` | 32 |
   * | `7` | 40 |
   * | `8` | 48 |
   * | `9` | 64 |
   */
  columnGap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.fontSizes`
   *
   * | token | value |
   * |:--|--:|
   * | `1` | 12 |
   * | `2` | 14 |
   * | `3` | 16 |
   * | `4` | 18 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `7` | 28 |
   * | `8` | 35 |
   * | `9` | 60 |
   */
  fontSize?: FontSizeToken | number;
  /**
   * `tokens.fontWeights`
   *
   * | token | value |
   * |:--|--:|
   * | `light` | 300 |
   * | `regular` | 400 |
   * | `medium` | 500 |
   * | `bold` | 700 |
   */
  fontWeight?: FontWeightToken | TextStyle['fontWeight'];
  /**
   * `tokens.lineHeights`
   *
   * Not defined in this theme.
   */
  lineHeight?: LineHeightToken | number;
  /**
   * `tokens.letterSpacings`
   *
   * Not defined in this theme.
   */
  letterSpacing?: LetterSpacingToken | number;
  /**
   * `tokens.zIndices`
   *
   * Not defined in this theme.
   */
  zIndex?: ZIndexToken | number;
  /**
   * Virtual prop: expands to `shadowColor` / `shadowOffset` / `shadowOpacity` / `shadowRadius` / `elevation`.
   *
   * `tokens.shadows`
   *
   * | token | offset (x, y) | radius | opacity | elevation | color |
   * |:--|--:|--:|--:|--:|:--|
   * | `2` | 0, 1 | 1.5 | 0.051 | 2 | #000000 |
   * | `3` | 0, 4 | 8 | 0.102 | 4 | #000000 |
   * | `4` | 0, 8 | 20 | 0.051 | 8 | #000000 |
   * | `5` | 0, 12 | 30 | 0.149 | 12 | #000000 |
   * | `6` | 0, 16 | 32 | 0.024 | 16 | #000055 |
   */
  shadow?: ShadowToken;
}

// ---------------------------------------------------------------------------
// Typography presets: themed.text.<path>(override?)
// ---------------------------------------------------------------------------

type TextVariant = (
  override?: TokenizeStyle<TextStyle, ThemedStyleProps>,
) => TextStyle;

export interface ThemedTextVariants {
  /**
   * `semanticTokens.text.text`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `text.1` | 12 | 16 | 0.03 | – |
   * | `text.2` | 14 | 20 | 0 | – |
   * | `text.3` | 16 | 24 | 0 | – |
   * | `text.4` | 18 | 26 | -0.045 | – |
   * | `text.5` | 20 | 28 | -0.1 | – |
   * | `text.6` | 24 | 30 | -0.15 | – |
   * | `text.7` | 28 | 36 | -0.21 | – |
   * | `text.8` | 35 | 40 | -0.35 | – |
   * | `text.9` | 60 | 60 | -1.5 | – |
   */
  text: {
    /**
     * `semanticTokens.text.text.1`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 12 | 16 | 0.03 | – |
     */
    1: TextVariant;
    /**
     * `semanticTokens.text.text.2`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 14 | 20 | 0 | – |
     */
    2: TextVariant;
    /**
     * `semanticTokens.text.text.3`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 16 | 24 | 0 | – |
     */
    3: TextVariant;
    /**
     * `semanticTokens.text.text.4`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 18 | 26 | -0.045 | – |
     */
    4: TextVariant;
    /**
     * `semanticTokens.text.text.5`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 20 | 28 | -0.1 | – |
     */
    5: TextVariant;
    /**
     * `semanticTokens.text.text.6`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 24 | 30 | -0.15 | – |
     */
    6: TextVariant;
    /**
     * `semanticTokens.text.text.7`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 28 | 36 | -0.21 | – |
     */
    7: TextVariant;
    /**
     * `semanticTokens.text.text.8`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 35 | 40 | -0.35 | – |
     */
    8: TextVariant;
    /**
     * `semanticTokens.text.text.9`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 60 | 60 | -1.5 | – |
     */
    9: TextVariant;
  };
  /**
   * `semanticTokens.text.heading`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `heading.1` | 12 | 16 | 0.03 | `bold` (700) |
   * | `heading.2` | 14 | 18 | 0 | `bold` (700) |
   * | `heading.3` | 16 | 22 | 0 | `bold` (700) |
   * | `heading.4` | 18 | 24 | -0.045 | `bold` (700) |
   * | `heading.5` | 20 | 26 | -0.1 | `bold` (700) |
   * | `heading.6` | 24 | 30 | -0.15 | `bold` (700) |
   * | `heading.7` | 28 | 36 | -0.21 | `bold` (700) |
   * | `heading.8` | 35 | 40 | -0.35 | `bold` (700) |
   * | `heading.9` | 60 | 60 | -1.5 | `bold` (700) |
   */
  heading: {
    /**
     * `semanticTokens.text.heading.1`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 12 | 16 | 0.03 | `bold` (700) |
     */
    1: TextVariant;
    /**
     * `semanticTokens.text.heading.2`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 14 | 18 | 0 | `bold` (700) |
     */
    2: TextVariant;
    /**
     * `semanticTokens.text.heading.3`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 16 | 22 | 0 | `bold` (700) |
     */
    3: TextVariant;
    /**
     * `semanticTokens.text.heading.4`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 18 | 24 | -0.045 | `bold` (700) |
     */
    4: TextVariant;
    /**
     * `semanticTokens.text.heading.5`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 20 | 26 | -0.1 | `bold` (700) |
     */
    5: TextVariant;
    /**
     * `semanticTokens.text.heading.6`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 24 | 30 | -0.15 | `bold` (700) |
     */
    6: TextVariant;
    /**
     * `semanticTokens.text.heading.7`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 28 | 36 | -0.21 | `bold` (700) |
     */
    7: TextVariant;
    /**
     * `semanticTokens.text.heading.8`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 35 | 40 | -0.35 | `bold` (700) |
     */
    8: TextVariant;
    /**
     * `semanticTokens.text.heading.9`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 60 | 60 | -1.5 | `bold` (700) |
     */
    9: TextVariant;
  };
}

// ---------------------------------------------------------------------------
// useThemed().tokens / useThemed().semanticTokens
// ---------------------------------------------------------------------------

export interface ThemedTokens {
  spacing: {
    1: 4;
    2: 8;
    3: 12;
    4: 16;
    5: 24;
    6: 32;
    7: 40;
    8: 48;
    9: 64;
  };
  radii: {
    1: 3;
    2: 4;
    3: 6;
    4: 8;
    5: 12;
    6: 16;
    full: 0;
  };
  fontSizes: {
    1: 12;
    2: 14;
    3: 16;
    4: 18;
    5: 20;
    6: 24;
    7: 28;
    8: 35;
    9: 60;
  };
  fontWeights: {
    light: '300';
    regular: '400';
    medium: '500';
    bold: '700';
  };
  shadows: {
    2: {
      shadowColor: '#000000';
      shadowOffset: {
        width: 0;
        height: 1;
      };
      shadowOpacity: 0.051;
      shadowRadius: 1.5;
      elevation: 2;
    };
    3: {
      shadowColor: '#000000';
      shadowOffset: {
        width: 0;
        height: 4;
      };
      shadowOpacity: 0.102;
      shadowRadius: 8;
      elevation: 4;
    };
    4: {
      shadowColor: '#000000';
      shadowOffset: {
        width: 0;
        height: 8;
      };
      shadowOpacity: 0.051;
      shadowRadius: 20;
      elevation: 8;
    };
    5: {
      shadowColor: '#000000';
      shadowOffset: {
        width: 0;
        height: 12;
      };
      shadowOpacity: 0.149;
      shadowRadius: 30;
      elevation: 12;
    };
    6: {
      shadowColor: '#000055';
      shadowOffset: {
        width: 0;
        height: 16;
      };
      shadowOpacity: 0.024;
      shadowRadius: 32;
      elevation: 16;
    };
  };
}

export interface ThemedSemanticTokens {
  /** Resolved for the current color scheme. */
  colors: {
    accent: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #fdfdfe | #11131f |
       */
      1: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #f7f9ff | #141726 |
       */
      2: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #edf2fe | #182449 |
       */
      3: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #e1e9ff | #1d2e62 |
       */
      4: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #d2deff | #253974 |
       */
      5: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #c1d0ff | #304384 |
       */
      6: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #abbdf9 | #3a4f97 |
       */
      7: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #8da4ef | #435db1 |
       */
      8: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #3e63dd | #3e63dd |
       */
      9: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #3358d4 | #5472e4 |
       */
      10: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #3a5bc7 | #9eb1ff |
       */
      11: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #1f2d5c | #d6e1ff |
       */
      12: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00008002 | #1133ff0f |
       */
      a1: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0040ff08 | #3354fa17 |
       */
      a2: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0047f112 | #2f62ff3c |
       */
      a3: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0044ff1e | #3566ff57 |
       */
      a4: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0044ff2d | #4171fd6b |
       */
      a5: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #003eff3e | #5178fd7c |
       */
      a6: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0037ed54 | #5a7fff90 |
       */
      a7: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0034dc72 | #5b81feac |
       */
      a8: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0031d2c1 | #4671ffdb |
       */
      a9: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #002ec9cc | #5c7efee3 |
       */
      a10: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #002bb7c5 | #9eb1ff |
       */
      a11: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #001046e0 | #d6e1ff |
       */
      a12: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #f5f8ffcc | #171d3b80 |
       */
      surface: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #3e63dd | #3e63dd |
       */
      indicator: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #3e63dd | #3e63dd |
       */
      track: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffff | #ffffff |
       */
      contrast: string;
    };
    gray: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #fcfcfd | #111113 |
       */
      1: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #f9f9fb | #18191b |
       */
      2: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #f0f0f3 | #212225 |
       */
      3: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #e8e8ec | #272a2d |
       */
      4: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #e0e1e6 | #2e3135 |
       */
      5: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #d9d9e0 | #363a3f |
       */
      6: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #cdced6 | #43484e |
       */
      7: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #b9bbc6 | #5a6169 |
       */
      8: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #8b8d98 | #696e77 |
       */
      9: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #80838d | #777b84 |
       */
      10: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #60646c | #b0b4ba |
       */
      11: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #1c2024 | #edeef0 |
       */
      12: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00005503 | #00000000 |
       */
      a1: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00005506 | #d8f4f609 |
       */
      a2: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0000330f | #ddeaf814 |
       */
      a3: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00002d17 | #d3edf81d |
       */
      a4: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0009321f | #d9edfe25 |
       */
      a5: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00002f26 | #d6ebfd30 |
       */
      a6: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00062e32 | #d9edff40 |
       */
      a7: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00083046 | #d9edff5d |
       */
      a8: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00051d74 | #dfebfd6d |
       */
      a9: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00071b7f | #e5edfd7b |
       */
      a10: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #0007149f | #f1f7feb5 |
       */
      a11: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #000509e3 | #fcfdffef |
       */
      a12: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffffcc | #1f212380 |
       */
      surface: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #8b8d98 | #696e77 |
       */
      indicator: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #8b8d98 | #696e77 |
       */
      track: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffff | #ffffff |
       */
      contrast: string;
    };
    color: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffff | #111113 |
       */
      background: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #00000066 | #00000099 |
       */
      overlay: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffff | #18191b |
       */
      'panel-solid': string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffffb3 | #d8f4f609 |
       */
      'panel-translucent': string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffffd9 | #00000040 |
       */
      surface: string;
    };
  };
  text: {
    text: {
      1: {
        fontSize: 12;
        lineHeight: 16;
        letterSpacing: 0.03;
      };
      2: {
        fontSize: 14;
        lineHeight: 20;
        letterSpacing: 0;
      };
      3: {
        fontSize: 16;
        lineHeight: 24;
        letterSpacing: 0;
      };
      4: {
        fontSize: 18;
        lineHeight: 26;
        letterSpacing: -0.045;
      };
      5: {
        fontSize: 20;
        lineHeight: 28;
        letterSpacing: -0.1;
      };
      6: {
        fontSize: 24;
        lineHeight: 30;
        letterSpacing: -0.15;
      };
      7: {
        fontSize: 28;
        lineHeight: 36;
        letterSpacing: -0.21;
      };
      8: {
        fontSize: 35;
        lineHeight: 40;
        letterSpacing: -0.35;
      };
      9: {
        fontSize: 60;
        lineHeight: 60;
        letterSpacing: -1.5;
      };
    };
    heading: {
      1: {
        fontSize: 12;
        lineHeight: 16;
        letterSpacing: 0.03;
        fontWeight: 'bold';
      };
      2: {
        fontSize: 14;
        lineHeight: 18;
        letterSpacing: 0;
        fontWeight: 'bold';
      };
      3: {
        fontSize: 16;
        lineHeight: 22;
        letterSpacing: 0;
        fontWeight: 'bold';
      };
      4: {
        fontSize: 18;
        lineHeight: 24;
        letterSpacing: -0.045;
        fontWeight: 'bold';
      };
      5: {
        fontSize: 20;
        lineHeight: 26;
        letterSpacing: -0.1;
        fontWeight: 'bold';
      };
      6: {
        fontSize: 24;
        lineHeight: 30;
        letterSpacing: -0.15;
        fontWeight: 'bold';
      };
      7: {
        fontSize: 28;
        lineHeight: 36;
        letterSpacing: -0.21;
        fontWeight: 'bold';
      };
      8: {
        fontSize: 35;
        lineHeight: 40;
        letterSpacing: -0.35;
        fontWeight: 'bold';
      };
      9: {
        fontSize: 60;
        lineHeight: 60;
        letterSpacing: -1.5;
        fontWeight: 'bold';
      };
    };
  };
}

// ---------------------------------------------------------------------------
// Instance
// ---------------------------------------------------------------------------

export interface ThemedTypes {
  style: ThemedStyleProps;
  textVariants: ThemedTextVariants;
  tokens: ThemedTokens;
  semanticTokens: ThemedSemanticTokens;
}

export const { ThemedProvider, useThemed, useColorMode } =
  createThemed<ThemedTypes>(themeConfig);
