/**
 * Regenerates `src/tokens.gen.ts` from the installed `@mui/material`.
 *
 *   pnpm --filter @react-native-rethemed/material-ui-tokens generate
 *
 * Bump the `@mui/material` devDependency version, run this, and review the
 * diff. Not exported from the package.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as muiColors from '@mui/material/colors';
import { createTheme } from '@mui/material/styles';
import {
  type ConvertedTheme,
  convertTheme,
  type MuiColors,
  type MuiTheme,
} from './convert';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../src/tokens.gen.ts');

const muiVersion: string = require('@mui/material/package.json').version;

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const NUMERIC_KEY = /^\d+(\.\d+)?$/;

function key(name: string): string {
  if (IDENTIFIER.test(name)) return name;
  if (NUMERIC_KEY.test(name) && String(Number(name)) === name) return name;
  return `'${name}'`;
}

function literal(value: unknown, indent: string): string {
  if (typeof value === 'string') return `'${value.replaceAll("'", "\\'")}'`;
  if (typeof value === 'number') return String(value);
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    // Small flat objects (`shadowOffset`) stay on one line.
    if (entries.every(([, v]) => typeof v !== 'object')) {
      const inline = `{ ${entries.map(([k, v]) => `${key(k)}: ${literal(v, indent)}`).join(', ')} }`;
      if (inline.length <= 40) return inline;
    }
    const inner = `${indent}  `;
    const lines = entries.map(
      ([k, v]) => `${inner}${key(k)}: ${literal(v, inner)},`,
    );
    return `{\n${lines.join('\n')}\n${indent}}`;
  }
  throw new Error(`cannot emit ${String(value)}`);
}

/**
 * Numeric keys (spacing, radii, shadows) in value order, the rest in source
 * order. Returns entries, since an object would move integer keys first
 * again. At runtime the object literal still lists integer keys first; the
 * order here only affects how the generated source reads.
 */
function ordered<T>(record: Record<string, T>): [string, T][] {
  const entries = Object.entries(record);
  if (entries.every(([k]) => NUMERIC_KEY.test(k))) {
    entries.sort(([a], [b]) => Number(a) - Number(b));
  }
  return entries;
}

function emitConst(
  name: keyof ConvertedTheme,
  value: Record<string, unknown>,
  doc: string,
  satisfies?: string,
): string {
  const lines = ordered(value).map(
    ([k, v]) => `  ${key(k)}: ${literal(v, '  ')},`,
  );
  const suffix = satisfies ? ` as const satisfies ${satisfies}` : ' as const';
  return `/** ${doc} */\nexport const ${name} = {\n${lines.join('\n')}\n}${suffix};\n`;
}

const theme = convertTheme(
  createTheme({ palette: { mode: 'light' } }) as unknown as MuiTheme,
  createTheme({ palette: { mode: 'dark' } }) as unknown as MuiTheme,
  muiColors as unknown as MuiColors,
);

const source = [
  `// Generated by scripts/generate.ts from @mui/material@${muiVersion}.`,
  '// Do not edit by hand: run `pnpm generate` instead.',
  '',
  'import type {',
  '  ShadowToken,',
  '  TextToken,',
  "} from '@react-native-rethemed/core/config';",
  '',
  emitConst(
    'colors',
    theme.colors,
    "Material UI's color palette (`@mui/material/colors`): `'<hue>.<shade>'`, plus `black` and `white`.",
  ),
  emitConst(
    'semanticColors',
    theme.semanticColors,
    'The default `palette` in light and dark mode. `divider` becomes `divider.default`.',
  ),
  emitConst(
    'typography',
    theme.typography,
    '`theme.typography` variants as text presets: rem and em in points at `htmlFontSize`, line heights absolute.',
    'Record<string, TextToken>',
  ),
  emitConst(
    'fontWeights',
    theme.fontWeights,
    '`typography.fontWeightLight` / `Regular` / `Medium` / `Bold`.',
  ),
  emitConst(
    'spacing',
    theme.spacing,
    '`theme.spacing(n)` for common factors: `padding: 2` is `theme.spacing(2)`.',
  ),
  emitConst(
    'radii',
    theme.radii,
    'Multiples of `shape.borderRadius`: `borderRadius: 2` is `sx={{ borderRadius: 2 }}`.',
  ),
  emitConst('zIndices', theme.zIndices, '`theme.zIndex`.'),
  emitConst(
    'shadows',
    theme.shadows,
    '`theme.shadows` by elevation, first layer only; `elevation` matches on Android.',
    'Record<string, ShadowToken>',
  ),
].join('\n');

writeFileSync(outFile, source);

// Let biome settle line breaks so the file passes `pnpm lint`.
execFileSync(
  process.execPath,
  [require.resolve('@biomejs/biome/bin/biome'), 'format', '--write', outFile],
  { stdio: 'inherit' },
);

console.log(`Wrote ${outFile} (@mui/material@${muiVersion})`);
