/**
 * Regenerates `src/tokens.gen.ts` from the registry snapshot in
 * `scripts/registry/` (refresh it first with `pnpm sync`).
 *
 *   pnpm --filter @react-native-rethemed/shadcn-ui-tokens generate
 *
 * Not exported from the package.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  BASE_COLORS,
  type BaseColor,
  type ConvertedTheme,
  type CssVars,
  convertRegistry,
} from './convert';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../src/tokens.gen.ts');

const readJson = (name: string) =>
  JSON.parse(readFileSync(resolve(here, 'registry', name), 'utf8'));
const source: { commit: string; syncedAt: string } = readJson('source.json');
const registry = Object.fromEntries(
  BASE_COLORS.map((base) => [base, readJson(`${base}.json`) as CssVars]),
) as Record<BaseColor, CssVars>;

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const NUMERIC_KEY = /^\d+(\.\d+)?$/;

function key(name: string): string {
  if (IDENTIFIER.test(name)) return name;
  if (NUMERIC_KEY.test(name) && String(Number(name)) === name) return name;
  return `'${name}'`;
}

function literal(value: unknown, indent: string): string {
  if (typeof value === 'string') return `'${value.replaceAll("'", "\\'")}'`;
  if (typeof value === 'number') return String(value);
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    // Small flat objects (`shadowOffset`) stay on one line.
    if (entries.every(([, v]) => typeof v !== 'object')) {
      const inline = `{ ${entries.map(([k, v]) => `${key(k)}: ${literal(v, indent)}`).join(', ')} }`;
      if (inline.length <= 40) return inline;
    }
    const inner = `${indent}  `;
    const lines = entries.map(
      ([k, v]) => `${inner}${key(k)}: ${literal(v, inner)},`,
    );
    return `{\n${lines.join('\n')}\n${indent}}`;
  }
  throw new Error(`cannot emit ${String(value)}`);
}

/**
 * Named keys (`px`) first, then numeric keys (spacing) in value order.
 * Returns entries, since an object would move integer keys first again. At
 * runtime the object literal still lists integer keys first; the order here
 * only affects how the generated source reads.
 */
function ordered<T>(record: Record<string, T>): [string, T][] {
  const entries = Object.entries(record);
  const numeric = entries.filter(([k]) => NUMERIC_KEY.test(k));
  if (numeric.length === 0) return entries;
  numeric.sort(([a], [b]) => Number(a) - Number(b));
  return [...entries.filter(([k]) => !NUMERIC_KEY.test(k)), ...numeric];
}

function emitConst(
  name: keyof ConvertedTheme,
  value: Record<string, unknown>,
  doc: string,
  satisfies?: string,
): string {
  const lines = ordered(value).map(
    ([k, v]) => `  ${key(k)}: ${literal(v, '  ')},`,
  );
  const suffix = satisfies ? ` as const satisfies ${satisfies}` : ' as const';
  return `/** ${doc} */\nexport const ${name} = {\n${lines.join('\n')}\n}${suffix};\n`;
}

const theme = convertRegistry(registry);

const source_ = [
  `// Generated by scripts/generate.ts from the shadcn/ui registry (shadcn-ui/ui@${source.commit.slice(0, 7)}, synced ${source.syncedAt}).`,
  '// Do not edit by hand: run `pnpm sync` and `pnpm generate` instead.',
  '',
  emitConst(
    'baseColors',
    theme.baseColors,
    "Each base color's `cssVarsV4` as top-level semantic colors with shadcn/ui's names (`primary`, `primary-foreground`, `chart-1`, `sidebar-ring`), oklch converted to hex.",
  ),
  emitConst(
    'radii',
    theme.radii,
    '`--radius` (0.625rem) and the `radius-*` scale shadcn/ui derives from it, in points.',
  ),
].join('\n');

writeFileSync(outFile, source_);

// Let biome settle line breaks so the file passes `pnpm lint`.
execFileSync(
  process.execPath,
  [require.resolve('@biomejs/biome/bin/biome'), 'format', '--write', outFile],
  { stdio: 'inherit' },
);

console.log(`Wrote ${outFile} (shadcn-ui/ui@${source.commit.slice(0, 7)})`);
