// Code generated by @react-native-rethemed/cli. DO NOT EDIT.
// Regenerate with: react-native-rethemed codegen src/shell/theme.ts

import type { TextStyle } from 'react-native';
import { createThemed, type TokenizeStyle } from '@react-native-rethemed/core';
import { themeConfig } from './theme';

// ---------------------------------------------------------------------------
// Token names
// ---------------------------------------------------------------------------

export type SemanticColorToken =
  | 'bg.canvas'
  | 'bg.surface'
  | 'bg.subtle'
  | 'bg.selected'
  | 'bg.backdrop'
  | 'fg.default'
  | 'fg.muted'
  | 'fg.subtle'
  | 'border.default'
  | 'border.subtle'
  | 'accent.solid'
  | 'accent.fg'
  | 'accent.contrast';
export type PrimitiveColorToken = 'white' | 'black';
/** Color props take both: semantic colors switch with light/dark, primitives are fixed. */
export type ColorToken = SemanticColorToken | PrimitiveColorToken;
export type RadiusToken =
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | 'full';
export type SpacingToken =
  | 0
  | 0.5
  | 1
  | 1.5
  | 2
  | 2.5
  | 3
  | 4
  | 5
  | 6
  | 8
  | 10;
export type FontSizeToken =
  | '2xs'
  | 'xs'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | '2xl';
export type FontWeightToken = 'normal' | 'medium' | 'semibold' | 'bold';
export type LineHeightToken = 'tight' | 'normal';
export type LetterSpacingToken = never;
export type ShadowToken = 'sm' | 'lg';
export type ZIndexToken = 'base';

// ---------------------------------------------------------------------------
// Token-aware style props. Each primitive picks the ones its RN style type
// has (see `TokenizeStyle` in core), so e.g. `color` never shows on View.
// ---------------------------------------------------------------------------

export interface ThemedStyleProps {
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  color?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  backgroundColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderTopColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderBottomColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderLeftColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderRightColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderStartColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderEndColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderBlockColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderBlockStartColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  borderBlockEndColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  tintColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  overlayColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  shadowColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  outlineColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  textShadowColor?: ColorToken;
  /**
   * `semanticTokens.colors`: switch with light/dark. Prefer these.
   *
   * | token | light | dark |
   * |:--|:--|:--|
   * | `bg.canvas` | #ffffff | #09090b |
   * | `bg.surface` | #fafafa | #121214 |
   * | `bg.subtle` | #f4f4f5 | #1c1c1f |
   * | `bg.selected` | #eef2ff | #1e1b4b |
   * | `bg.backdrop` | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
   * | `fg.default` | #18181b | #fafafa |
   * | `fg.muted` | #52525b | #a1a1aa |
   * | `fg.subtle` | #a1a1aa | #71717a |
   * | `border.default` | #e4e4e7 | #27272a |
   * | `border.subtle` | #f4f4f5 | #1c1c1f |
   * | `accent.solid` | #4f46e5 | #818cf8 |
   * | `accent.fg` | #4338ca | #a5b4fc |
   * | `accent.contrast` | #ffffff | #1e1b4b |
   *
   * `tokens.colors`: Fixed colors, the same in light and dark.
   *
   * | token | value |
   * |:--|:--|
   * | `white` | #ffffff |
   * | `black` | #000000 |
   */
  textDecorationColor?: ColorToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderTopLeftRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderTopRightRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderTopStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderTopEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderBottomLeftRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderBottomRightRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderBottomStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderBottomEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderStartStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderStartEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderEndStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * | token | value |
   * |:--|--:|
   * | `sm` | 4 |
   * | `md` | 8 |
   * | `lg` | 12 |
   * | `xl` | 16 |
   * | `full` | 9999 |
   */
  borderEndEndRadius?: RadiusToken;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  padding?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingTop?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingBottom?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingLeft?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingRight?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingHorizontal?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingVertical?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingBlock?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingBlockStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingBlockEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingInline?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingInlineStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  paddingInlineEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  margin?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginTop?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginBottom?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginLeft?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginRight?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginHorizontal?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginVertical?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginBlock?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginBlockStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginBlockEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginInline?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginInlineStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  marginInlineEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  gap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  rowGap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `0.5` | 2 |
   * | `1` | 4 |
   * | `1.5` | 6 |
   * | `2` | 8 |
   * | `2.5` | 10 |
   * | `3` | 12 |
   * | `4` | 16 |
   * | `5` | 20 |
   * | `6` | 24 |
   * | `8` | 32 |
   * | `10` | 40 |
   */
  columnGap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.fontSizes`
   *
   * | token | value |
   * |:--|--:|
   * | `2xs` | 10 |
   * | `xs` | 12 |
   * | `sm` | 14 |
   * | `md` | 16 |
   * | `lg` | 18 |
   * | `xl` | 20 |
   * | `2xl` | 24 |
   */
  fontSize?: FontSizeToken | number;
  /**
   * `tokens.fontWeights`
   *
   * | token | value |
   * |:--|--:|
   * | `normal` | 400 |
   * | `medium` | 500 |
   * | `semibold` | 600 |
   * | `bold` | 700 |
   */
  fontWeight?: FontWeightToken | TextStyle['fontWeight'];
  /**
   * Ratios of `fontSize`: a token resolves to `fontSize × ratio`, using the style's own `fontSize` or else the default font size, `md` (16). A raw number is an absolute line height.
   *
   * `tokens.lineHeights`
   *
   * | token | value |
   * |:--|--:|
   * | `tight` | ×1.25 |
   * | `normal` | ×1.5 |
   */
  lineHeight?: LineHeightToken | number;
  /**
   * `tokens.letterSpacings`
   *
   * Not defined in this theme.
   */
  letterSpacing?: LetterSpacingToken | number;
  /**
   * `tokens.zIndices`
   *
   * | token | value |
   * |:--|--:|
   * | `base` | 0 |
   */
  zIndex?: ZIndexToken | number;
  /**
   * Virtual prop: expands to `shadowColor` / `shadowOffset` / `shadowOpacity` / `shadowRadius` / `elevation`.
   *
   * `tokens.shadows`
   *
   * | token | offset (x, y) | radius | opacity | elevation | color |
   * |:--|--:|--:|--:|--:|:--|
   * | `sm` | 0, 1 | 2 | 0.08 | 1 | #000000 |
   * | `lg` | 4, 0 | 16 | 0.2 | 16 | #000000 |
   */
  shadow?: ShadowToken;
}

// ---------------------------------------------------------------------------
// Typography presets: themed.text.<path>(override?)
// ---------------------------------------------------------------------------

type TextVariant = (
  override?: TokenizeStyle<TextStyle, ThemedStyleProps>,
) => TextStyle;

export interface ThemedTextVariants {

}

// ---------------------------------------------------------------------------
// useThemed().tokens / useThemed().semanticTokens
// ---------------------------------------------------------------------------

export interface ThemedTokens {
  colors: {
    white: '#ffffff';
    black: '#000000';
  };
  radii: {
    sm: 4;
    md: 8;
    lg: 12;
    xl: 16;
    full: 9999;
  };
  spacing: {
    0: 0;
    1: 4;
    2: 8;
    3: 12;
    4: 16;
    5: 20;
    6: 24;
    8: 32;
    10: 40;
    0.5: 2;
    1.5: 6;
    2.5: 10;
  };
  fontSizes: {
    '2xs': 10;
    xs: 12;
    sm: 14;
    md: 16;
    lg: 18;
    xl: 20;
    '2xl': 24;
  };
  fontWeights: {
    normal: '400';
    medium: '500';
    semibold: '600';
    bold: '700';
  };
  lineHeights: {
    tight: 1.25;
    normal: 1.5;
  };
  zIndices: {
    base: 0;
  };
  shadows: {
    sm: {
      shadowColor: '#000000';
      shadowOffset: {
        width: 0;
        height: 1;
      };
      shadowOpacity: 0.08;
      shadowRadius: 2;
      elevation: 1;
    };
    lg: {
      shadowColor: '#000000';
      shadowOffset: {
        width: 4;
        height: 0;
      };
      shadowOpacity: 0.2;
      shadowRadius: 16;
      elevation: 16;
    };
  };
}

export interface ThemedSemanticTokens {
  /** Resolved for the current color scheme. */
  colors: {
    bg: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffff | #09090b |
       */
      canvas: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #fafafa | #121214 |
       */
      surface: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #f4f4f5 | #1c1c1f |
       */
      subtle: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #eef2ff | #1e1b4b |
       */
      selected: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | rgba(9, 9, 11, 0.4) | rgba(0, 0, 0, 0.6) |
       */
      backdrop: string;
    };
    fg: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #18181b | #fafafa |
       */
      default: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #52525b | #a1a1aa |
       */
      muted: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #a1a1aa | #71717a |
       */
      subtle: string;
    };
    border: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #e4e4e7 | #27272a |
       */
      default: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #f4f4f5 | #1c1c1f |
       */
      subtle: string;
    };
    accent: {
      /**
       * | light | dark |
       * |:--|:--|
       * | #4f46e5 | #818cf8 |
       */
      solid: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #4338ca | #a5b4fc |
       */
      fg: string;
      /**
       * | light | dark |
       * |:--|:--|
       * | #ffffff | #1e1b4b |
       */
      contrast: string;
    };
  };
  text: {};
}

// ---------------------------------------------------------------------------
// Instance
// ---------------------------------------------------------------------------

export interface ThemedTypes {
  style: ThemedStyleProps;
  textVariants: ThemedTextVariants;
  tokens: ThemedTokens;
  semanticTokens: ThemedSemanticTokens;
}

export const { ThemedProvider, useThemed, useColorMode } =
  createThemed<ThemedTypes>(themeConfig);
