/**
 * Regenerates `src/tokens.gen.ts` from the installed `@pandacss/preset-panda`.
 *
 *   pnpm --filter @react-native-rethemed/panda-css-tokens generate
 *
 * Bump the preset's devDependency version, run this, and review the diff.
 * Not exported from the package.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { preset } from '@pandacss/preset-panda';
import { type ConvertedTheme, convertPreset } from './convert';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(here, '../src/tokens.gen.ts');

const presetVersion: string =
  require('@pandacss/preset-panda/package.json').version;

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;
const NUMERIC_KEY = /^\d+(\.\d+)?$/;

function key(name: string): string {
  if (IDENTIFIER.test(name)) return name;
  if (NUMERIC_KEY.test(name) && String(Number(name)) === name) return name;
  return `'${name}'`;
}

function literal(value: unknown, indent: string): string {
  if (typeof value === 'string') return `'${value.replaceAll("'", "\\'")}'`;
  if (typeof value === 'number') return String(value);
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    // Small flat objects (`shadowOffset`) stay on one line.
    if (entries.every(([, v]) => typeof v !== 'object')) {
      const inline = `{ ${entries.map(([k, v]) => `${key(k)}: ${literal(v, indent)}`).join(', ')} }`;
      if (inline.length <= 40) return inline;
    }
    const inner = `${indent}  `;
    const lines = entries.map(
      ([k, v]) => `${inner}${key(k)}: ${literal(v, inner)},`,
    );
    return `{\n${lines.join('\n')}\n${indent}}`;
  }
  throw new Error(`cannot emit ${String(value)}`);
}

/**
 * Numeric keys (spacing) in value order, the rest in preset order. Returns
 * entries, since an object would move integer keys first again. At runtime
 * the object literal still lists integer keys first; the order here only
 * affects how the generated source reads.
 */
function ordered<T>(record: Record<string, T>): [string, T][] {
  const entries = Object.entries(record);
  if (entries.every(([k]) => NUMERIC_KEY.test(k))) {
    entries.sort(([a], [b]) => Number(a) - Number(b));
  }
  return entries;
}

function emitConst(
  name: keyof ConvertedTheme,
  value: Record<string, unknown>,
  doc: string,
  satisfies?: string,
): string {
  const lines = ordered(value).map(
    ([k, v]) => `  ${key(k)}: ${literal(v, '  ')},`,
  );
  const suffix = satisfies ? ` as const satisfies ${satisfies}` : ' as const';
  return `/** ${doc} */\nexport const ${name} = {\n${lines.join('\n')}\n}${suffix};\n`;
}

const theme = convertPreset(preset);

const source = [
  `// Generated by scripts/generate.ts from @pandacss/preset-panda@${presetVersion}.`,
  '// Do not edit by hand: run `pnpm generate` instead.',
  '',
  "import type { ShadowToken } from '@react-native-rethemed/core/config';",
  '',
  emitConst(
    'colors',
    theme.colors,
    "Panda's palette (Tailwind's), converted from oklch to hex. `current` is omitted.",
  ),
  emitConst('radii', theme.radii, 'Border radii, in points (1rem = 16).'),
  emitConst('spacing', theme.spacing, 'Spacing scale, in points (1rem = 16).'),
  emitConst('fontSizes', theme.fontSizes, 'Font sizes, in points (1rem = 16).'),
  emitConst('fontWeights', theme.fontWeights, 'Font weights.'),
  emitConst(
    'lineHeights',
    theme.lineHeights,
    'Line heights, as ratios of `fontSize`.',
  ),
  emitConst(
    'letterSpacings',
    theme.letterSpacings,
    'Letter spacings: em values converted to points at a 16px font size.',
  ),
  emitConst(
    'shadows',
    theme.shadows,
    'Box shadows as single-layer RN shadows. Inset shadows are omitted.',
    'Record<string, ShadowToken>',
  ),
].join('\n');

writeFileSync(outFile, source);

// Let biome settle line breaks so the file passes `pnpm lint`.
execFileSync(
  process.execPath,
  [require.resolve('@biomejs/biome/bin/biome'), 'format', '--write', outFile],
  { stdio: 'inherit' },
);

console.log(`Wrote ${outFile} (@pandacss/preset-panda@${presetVersion})`);
