// Code generated by @react-native-rethemed/cli. DO NOT EDIT.
// Regenerate with: react-native-rethemed codegen example/theme.ts --docs example/themed.md

import type { TextStyle } from 'react-native';
import { createThemed, type TokenizeStyle } from '@react-native-rethemed/core';
import { themeConfig } from './theme';

// ---------------------------------------------------------------------------
// Token names
// ---------------------------------------------------------------------------

export type SemanticColorToken = never;
export type PrimitiveColorToken = never;
/** Color props take both: semantic colors switch with light/dark, primitives are fixed. */
export type ColorToken = SemanticColorToken | PrimitiveColorToken;
export type RadiusToken = never;
export type SpacingToken =
  | 0
  | 2
  | 4
  | 6
  | 8
  | 10
  | 16
  | 24
  | 32
  | 40
  | 48
  | 56
  | 64
  | 72;
export type FontSizeToken = never;
export type FontWeightToken = never;
export type LineHeightToken = never;
export type LetterSpacingToken = never;
export type ShadowToken = never;
export type ZIndexToken = never;

// ---------------------------------------------------------------------------
// Token-aware style props. Each primitive picks the ones its RN style type
// has (see `TokenizeStyle` in core), so e.g. `color` never shows on View.
// ---------------------------------------------------------------------------

export interface ThemedStyleProps {
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  color?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  backgroundColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderTopColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderBottomColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderLeftColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderRightColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderStartColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderEndColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderBlockColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderBlockStartColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  borderBlockEndColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  tintColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  overlayColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  shadowColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  outlineColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  textShadowColor?: ColorToken;
  /**
   * `semanticTokens.colors` / `tokens.colors`
   *
   * Not defined in this theme. No color token is accepted here; pass colors in a second plain style object.
   */
  textDecorationColor?: ColorToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderTopLeftRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderTopRightRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderTopStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderTopEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderBottomLeftRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderBottomRightRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderBottomStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderBottomEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderStartStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderStartEndRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderEndStartRadius?: RadiusToken;
  /**
   * `tokens.radii`
   *
   * Not defined in this theme.
   */
  borderEndEndRadius?: RadiusToken;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  padding?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingTop?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingBottom?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingLeft?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingRight?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingHorizontal?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingVertical?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingBlock?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingBlockStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingBlockEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingInline?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingInlineStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  paddingInlineEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  margin?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginTop?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginBottom?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginLeft?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginRight?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginHorizontal?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginVertical?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginBlock?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginBlockStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginBlockEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginInline?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginInlineStart?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  marginInlineEnd?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  gap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  rowGap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.spacing`
   *
   * | token | value |
   * |:--|--:|
   * | `0` | 0 |
   * | `2` | 2 |
   * | `4` | 4 |
   * | `6` | 6 |
   * | `8` | 8 |
   * | `10` | 10 |
   * | `16` | 16 |
   * | `24` | 24 |
   * | `32` | 32 |
   * | `40` | 40 |
   * | `48` | 48 |
   * | `56` | 56 |
   * | `64` | 64 |
   * | `72` | 72 |
   */
  columnGap?: SpacingToken | 'auto' | `${number}%`;
  /**
   * `tokens.fontSizes`
   *
   * Not defined in this theme.
   */
  fontSize?: FontSizeToken | number;
  /**
   * `tokens.fontWeights`
   *
   * Not defined in this theme.
   */
  fontWeight?: FontWeightToken | TextStyle['fontWeight'];
  /**
   * `tokens.lineHeights`
   *
   * Not defined in this theme.
   */
  lineHeight?: LineHeightToken | number;
  /**
   * `tokens.letterSpacings`
   *
   * Not defined in this theme.
   */
  letterSpacing?: LetterSpacingToken | number;
  /**
   * `tokens.zIndices`
   *
   * Not defined in this theme.
   */
  zIndex?: ZIndexToken | number;
  /**
   * Virtual prop: expands to `shadowColor` / `shadowOffset` / `shadowOpacity` / `shadowRadius` / `elevation`.
   *
   * `tokens.shadows`
   *
   * Not defined in this theme.
   */
  shadow?: ShadowToken;
}

// ---------------------------------------------------------------------------
// Typography presets: themed.text.<path>(override?)
// ---------------------------------------------------------------------------

type TextVariant = (
  override?: TokenizeStyle<TextStyle, ThemedStyleProps>,
) => TextStyle;

export interface ThemedTextVariants {
  /**
   * `semanticTokens.text.display`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `display.lg` | 57 | 64 | -0.25 | 400 |
   * | `display.md` | 45 | 52 | 0 | 400 |
   * | `display.sm` | 36 | 44 | 0 | 400 |
   */
  display: {
    /**
     * `semanticTokens.text.display.lg`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 57 | 64 | -0.25 | 400 |
     */
    lg: TextVariant;
    /**
     * `semanticTokens.text.display.md`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 45 | 52 | 0 | 400 |
     */
    md: TextVariant;
    /**
     * `semanticTokens.text.display.sm`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 36 | 44 | 0 | 400 |
     */
    sm: TextVariant;
  };
  /**
   * `semanticTokens.text.headline`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `headline.lg` | 32 | 40 | 0 | 400 |
   * | `headline.md` | 28 | 36 | 0 | 400 |
   * | `headline.sm` | 24 | 32 | 0 | 400 |
   */
  headline: {
    /**
     * `semanticTokens.text.headline.lg`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 32 | 40 | 0 | 400 |
     */
    lg: TextVariant;
    /**
     * `semanticTokens.text.headline.md`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 28 | 36 | 0 | 400 |
     */
    md: TextVariant;
    /**
     * `semanticTokens.text.headline.sm`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 24 | 32 | 0 | 400 |
     */
    sm: TextVariant;
  };
  /**
   * `semanticTokens.text.title`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `title.lg` | 22 | 28 | 0 | 400 |
   * | `title.md` | 16 | 24 | 0.15 | 500 |
   * | `title.sm` | 14 | 20 | 0.1 | 500 |
   */
  title: {
    /**
     * `semanticTokens.text.title.lg`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 22 | 28 | 0 | 400 |
     */
    lg: TextVariant;
    /**
     * `semanticTokens.text.title.md`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 16 | 24 | 0.15 | 500 |
     */
    md: TextVariant;
    /**
     * `semanticTokens.text.title.sm`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 14 | 20 | 0.1 | 500 |
     */
    sm: TextVariant;
  };
  /**
   * `semanticTokens.text.body`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `body.lg` | 16 | 24 | 0.5 | 400 |
   * | `body.md` | 14 | 20 | 0.25 | 400 |
   * | `body.sm` | 12 | 16 | 0.4 | 400 |
   */
  body: {
    /**
     * `semanticTokens.text.body.lg`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 16 | 24 | 0.5 | 400 |
     */
    lg: TextVariant;
    /**
     * `semanticTokens.text.body.md`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 14 | 20 | 0.25 | 400 |
     */
    md: TextVariant;
    /**
     * `semanticTokens.text.body.sm`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 12 | 16 | 0.4 | 400 |
     */
    sm: TextVariant;
  };
  /**
   * `semanticTokens.text.label`
   *
   * | preset | fontSize | lineHeight | letterSpacing | fontWeight |
   * |:--|--:|--:|--:|--:|
   * | `label.lg` | 14 | 20 | 0.1 | 500 |
   * | `label.md` | 12 | 16 | 0.5 | 500 |
   * | `label.sm` | 11 | 16 | 0.5 | 500 |
   */
  label: {
    /**
     * `semanticTokens.text.label.lg`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 14 | 20 | 0.1 | 500 |
     */
    lg: TextVariant;
    /**
     * `semanticTokens.text.label.md`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 12 | 16 | 0.5 | 500 |
     */
    md: TextVariant;
    /**
     * `semanticTokens.text.label.sm`
     *
     * | fontSize | lineHeight | letterSpacing | fontWeight |
     * |--:|--:|--:|--:|
     * | 11 | 16 | 0.5 | 500 |
     */
    sm: TextVariant;
  };
}

// ---------------------------------------------------------------------------
// useThemed().tokens / useThemed().semanticTokens
// ---------------------------------------------------------------------------

export interface ThemedTokens {
  spacing: {
    0: 0;
    2: 2;
    4: 4;
    6: 6;
    8: 8;
    10: 10;
    16: 16;
    24: 24;
    32: 32;
    40: 40;
    48: 48;
    56: 56;
    64: 64;
    72: 72;
  };
}

export interface ThemedSemanticTokens {
  /** Resolved for the current color scheme. */
  colors: {};
  text: {
    display: {
      lg: {
        fontSize: 57;
        lineHeight: 64;
        letterSpacing: -0.25;
        fontWeight: '400';
      };
      md: {
        fontSize: 45;
        lineHeight: 52;
        letterSpacing: 0;
        fontWeight: '400';
      };
      sm: {
        fontSize: 36;
        lineHeight: 44;
        letterSpacing: 0;
        fontWeight: '400';
      };
    };
    headline: {
      lg: {
        fontSize: 32;
        lineHeight: 40;
        letterSpacing: 0;
        fontWeight: '400';
      };
      md: {
        fontSize: 28;
        lineHeight: 36;
        letterSpacing: 0;
        fontWeight: '400';
      };
      sm: {
        fontSize: 24;
        lineHeight: 32;
        letterSpacing: 0;
        fontWeight: '400';
      };
    };
    title: {
      lg: {
        fontSize: 22;
        lineHeight: 28;
        letterSpacing: 0;
        fontWeight: '400';
      };
      md: {
        fontSize: 16;
        lineHeight: 24;
        letterSpacing: 0.15;
        fontWeight: '500';
      };
      sm: {
        fontSize: 14;
        lineHeight: 20;
        letterSpacing: 0.1;
        fontWeight: '500';
      };
    };
    body: {
      lg: {
        fontSize: 16;
        lineHeight: 24;
        letterSpacing: 0.5;
        fontWeight: '400';
      };
      md: {
        fontSize: 14;
        lineHeight: 20;
        letterSpacing: 0.25;
        fontWeight: '400';
      };
      sm: {
        fontSize: 12;
        lineHeight: 16;
        letterSpacing: 0.4;
        fontWeight: '400';
      };
    };
    label: {
      lg: {
        fontSize: 14;
        lineHeight: 20;
        letterSpacing: 0.1;
        fontWeight: '500';
      };
      md: {
        fontSize: 12;
        lineHeight: 16;
        letterSpacing: 0.5;
        fontWeight: '500';
      };
      sm: {
        fontSize: 11;
        lineHeight: 16;
        letterSpacing: 0.5;
        fontWeight: '500';
      };
    };
  };
}

// ---------------------------------------------------------------------------
// Instance
// ---------------------------------------------------------------------------

export interface ThemedTypes {
  style: ThemedStyleProps;
  textVariants: ThemedTextVariants;
  tokens: ThemedTokens;
  semanticTokens: ThemedSemanticTokens;
}

export const { ThemedProvider, useThemed, useColorMode } =
  createThemed<ThemedTypes>(themeConfig);
